### ISSUE TITLE
code coin

### ISSUE THREAD

**Issue by Noname400** [iceland2k14/secp256k1#1]
pls. add code coin 
def privatekey_to_address
add a currency code to create addresses so that you can work with altcoins

**Comment by iceland2k14** [comment]
First attempt with 7 coins added. Please test.
```privatekey_to_coinaddress(coin_type, addr_type, iscompressed, pvk_int)```
coin_type = 0,21,9,15,19,23,12 for BTC, LTC, BTG, DGB, GRS, MONA, DASH.
