### ISSUE TITLE
Incorrect ice.btc_pvk_to_wif

### ISSUE THREAD

**Issue by boodooboo** [iceland2k14/secp256k1#17]
Hi. Thank you for your work. But...

`import secp256k1 as ice

addr = ice.btc_wif_to_pvk_hex('L3kQp4CrH2uc5bCRZhiS5sEGMpmcRZdpAhmWLRfMmufGTAW3ddfY')

wif = ice.btc_pvk_to_wif('c2d15fb4e3649b708c4ed87392bcf6df704db45cec5e762a1a52a9502df54e50')

print (addr)
print (wif)`

addr = c2d15fb4e3649b708c4ed87392bcf6df704db45cec5e762a1a52a9502df54e50; correct
wif = L3kQp4CrH2uc5bCRZhiS5sEGMpmcRZdpAhmWLRfMmufGTA**RdCfsV**; incorrect

Correct - L3kQp4CrH2uc5bCRZhiS5sEGMpmcRZdpAhmWLRfMmufGTA**W3ddfY**

Thanks.

**Comment by iceland2k14** [comment]
Strange... For me it is working OK. See the image .......
![image](https://user-images.githubusercontent.com/75991805/167241322-06b8f4cc-fe10-4acb-84f6-94dd8c886d7e.png)

Can you tell me which Python Version and which OS it is happening. Maybe just for safety re-download files from this repo and confirm. I might check too.

**Comment by boodooboo** [comment]
Python 3.9.10 (b332b321bbaa72bffb0207da5b7fe4c38047d3b2, Mar 16 2022, 16:03:21)
[PyPy 7.3.9 with MSC v.1929 64 bit (AMD64)]

Windows 10

Installed the library via Anaconda. It works fine. Thanks.
