### ISSUE TITLE
Please help: run > py secp256k1 ?

### ISSUE THREAD

**Issue by liodragon** [iceland2k14/secp256k1#19]
Please help:
run > python secp256k1.py
or any way:
#1.
 > python3 secp256k1.py
get it response:::
 File "secp256k1.py", line 527, in <module>
    def point_sequential_increment_P2_mcpu(num, pubkey1_bytes, mcpu=os.cpu_count()):
AttributeError: 'module' object has no attribute 'cpu_count'
#2. &&&
> python3 icehex.py
Traceback (most recent call last):
  File "C:\Users\***\icehex.py", line 2, in <module>
    from rich.console import Console
#3. &&&
> python icehex.py
  File "icehex.py", line 6
SyntaxError: Non-ASCII character '\xf0' in file icehex.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by iceland2k14** [comment]
Please see all the examples in Readme.
