### ISSUE TITLE
ice_secp256k1.dll Windows 10 error...

### ISSUE THREAD

**Issue by Jolly-Joker-71** [iceland2k14/secp256k1#23]
Python 3.9.12 under (windows 10 Pro)

Traceback (most recent call last):
  File "H:\Ramset\RANDBITS\random bits\Random.seed\BTC RANDOM SEED #64 II.py", line 4, in <module>
    import secp256k1 as ice
  File "H:\Ramset\RANDBITS\random bits\Random.seed\secp256k1.py", line 22, in <module>
    ice = ctypes.CDLL(pathdll)
  File "C:\Programs\Python\Python38\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'H:\Ramset\RANDBITS\random bits\Random.seed\ice_secp256k1.dll' (or one of its dependencies). Try using the full path with constructor syntax.

This problem occurs since windows 10 update to version 21H2... the dll file is not found even though it is present in the folder..

**Comment by iceland2k14** [comment]
Windows crazy behavior. Anyway can you please test if this solves your problem.....
Edit This Line
https://github.com/iceland2k14/secp256k1/blob/691e238c4a05c4bc93959fa339df341f24113919/secp256k1.py#L22
And change it to this
ice = ctypes.CDLL(pathdll, winmode=0)

**Comment by Jolly-Joker-71** [comment]
Perfect!!! Many many thanks for your fast fix this problem!!!
