### ISSUE TITLE
_point_sequential_decrement and Fill_in_bloom

### ISSUE THREAD

**Issue by omskns** [iceland2k14/secp256k1#28]
Hello, little problem.
`
P='02504673bb8f9a16e40227b4ee12fb8d940630cb687fbc98c1747493d18e22f39c'

P = ice.pub2upub('02504673bb8f9a16e40227b4ee12fb8d940630cb687fbc98c1747493d18e22f39c')
xx=ice._point_sequential_decrement(15, P)
for t in range(10):
    OnePub = xx[t*65:t*65+65]
    print(ice.point_to_cpub(OnePub));
_bits, _hashes, _bf =ice.Fill_in_bloom(xx, _fp = 0.000001)
ice.dump_bloom_file('my_bloom_file3.bin',_bits, _hashes, _bf)
xsxa='023df3506a9994ad4a28bf59a14fecd436a2871d257129d6b3bbd02a9d5cafaef5'
xsxa = ice.pub2upub(xsxa)
print(ice.check_in_bloom(xsxa, _bits, _hashes, _bf))`

the xsxa public key in byte representation is exactly contained in the array passed to the "Fill_in_bloom" function
However, checking for presence in bloom - returns False

PS public keys obtained using the "point_subtraction" function and added to bloom are checked and found.
"check_in_bloom" function returns true

**Comment by iceland2k14** [comment]
xx should be a List of elements not a byte array.
xsxa is same format as input List elements. Here for example in hex strings.

**Comment by dry1515** [comment]
> Hello, little problem. ` P='02504673bb8f9a16e40227b4ee12fb8d940630cb687fbc98c1747493d18e22f39c'
> 
> P = ice.pub2upub('02504673bb8f9a16e40227b4ee12fb8d940630cb687fbc98c1747493d18e22f39c') xx=ice._point_sequential_decrement(15, P) for t in range(10): OnePub = xx[t_65:t_65+65] print(ice.point_to_cpub(OnePub)); _bits, _hashes, _bf =ice.Fill_in_bloom(xx, _fp = 0.000001) ice.dump_bloom_file('my_bloom_file3.bin',_bits, _hashes, _bf) xsxa='023df3506a9994ad4a28bf59a14fecd436a2871d257129d6b3bbd02a9d5cafaef5' xsxa = ice.pub2upub(xsxa) print(ice.check_in_bloom(xsxa, _bits, _hashes, _bf))`
> 
> the xsxa public key in byte representation is exactly contained in the array passed to the "Fill_in_bloom" function However, checking for presence in bloom - returns False
> 
> PS public keys obtained using the "point_subtraction" function and added to bloom are checked and found. "check_in_bloom" function returns true

from where did you find this public key.key 023df3506a9994ad4a28bf59a14fecd436a2871d257129d6b3bbd02a9d5cafaef5 what is the private key from it?
