### ISSUE TITLE
point_multiplication is slow

### ISSUE THREAD

**Issue by maninder95** [iceland2k14/secp256k1#33]
I get about 400/second with point_multiplication, while scalar_multiplication is about 23K/second.
Please advice

EDIT: fixed typo

**Comment by AlexCurl** [comment]
Probably because of this:
def point_multiplication(k, P):
    ''' k=scalar. P = Input Point. Output is 65 bytes uncompressed pubkey '''
    if type(P) == int: k,P = P,k
    def bits(k):
        while k:
            yield k & 1
            k >>= 1
    result = Zero
    addend = P
    for bit in bits(k):
        if bit == 1: result=point_addition(result,addend)
        addend=point_doubling(addend)
    return result
ice.scalar_multiplication is pure c implementation

**Comment by iceland2k14** [comment]
Not Any More. Fixed in new version
