### ISSUE TITLE
Error then run

### ISSUE THREAD

**Issue by Hurd8x** [iceland2k14/secp256k1#38]
File "test.py", line 1, in <module>
    import secp256k1 as ice
  File "/home/xman/secp256k1/secp256k1.py", line 30, in <module>
    ice = ctypes.CDLL(pathdll)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xman/secp256k1/ice_secp256k1.so: cannot open shared object file: No such file or directory

How to solve this ?

thanks

**Comment by Hurd8x** [comment]
> This occurred to me a few times. I narrowed it down to the cloud infrastructure that had an arm processor. Not sure if it's the same for you.
> 
> You can try the forked version to see if it helps you.

hello, were is to get firked vesrsion for arm ?

thx

**Comment by WrongTurn-1** [comment]
https://github.com/citb0in/ice_secp256k1/tree/patch-1

**Comment by iceland2k14** [comment]
ARM is not supported. Path location is updated
