### ISSUE TITLE
pubkey_to_coinaddress

### ISSUE THREAD

**Issue by paschok81** [iceland2k14/secp256k1#41]
Hello. 
Thank you for your work. Is it possible to add pubkey_to_coinaddress?

**Comment by RDmitriev** [comment]
Already have **ice.pubkey_to_address**

**Comment by paschok81** [comment]
> Already have **ice.pubkey_to_address**

This one only works with Bitcoin. I needed it to work with other coins. For example, like Ice.privatekey_to_**coin**address

**Comment by RDmitriev** [comment]
See function parameters

```python
def pubkey_to_address(addr_type, iscompressed, pubkey_bytes):
```
**iscompressed** (True or False)


**addr_type**
COIN_BTC  = 0
COIN_BSV  = 1
COIN_BTCD = 2
COIN_ARG  = 3
COIN_AXE  =	4
COIN_BC   = 5
COIN_BCH  = 6
COIN_BSD  =	7
COIN_BTDX = 8 
COIN_BTG  =	9
COIN_BTX  =	10
COIN_CHA  =	11
COIN_DASH = 12
COIN_DCR  =	13
COIN_DFC  =	14
COIN_DGB  =	15
COIN_DOGE = 16
COIN_FAI  =	17
COIN_FTC  =	18
COIN_GRS  =	19
COIN_JBS  =	20
COIN_LTC  =	21
COIN_MEC  =	22
COIN_MONA = 23
COIN_MZC  =	24
COIN_PIVX = 25
COIN_POLIS= 26
COIN_RIC  = 27
COIN_STRAT= 28
COIN_SMART= 29
COIN_VIA  = 30
COIN_XMY  =	31
COIN_ZEC  =	32
COIN_ZCL  =	33
COIN_ZERO = 34
COIN_ZEN  =	35
COIN_TENT = 36
COIN_ZEIT = 37
COIN_VTC  =	38
COIN_UNO  =	39
COIN_SKC  =	40
COIN_RVN  =	41
COIN_PPC  =	42
COIN_OMC  =	43
COIN_OK   =	44
COIN_NMC  =	45
COIN_NLG  =	46
COIN_LBRY =	47
COIN_DNR  =	48
COIN_BWK  =	49

**Comment by paschok81** [comment]
> Уже есть **Ice.pubkey_to_address**

Don't confuse **coin_type** and **addr_type**

**Comment by iceland2k14** [comment]
@paschok81  Too late but now done.
