### ISSUE TITLE
site virustotal claims that there is a signature for a possible attack inside the DLL.

### ISSUE THREAD

**Issue by Maxim-MDProjects** [iceland2k14/secp256k1#44]
You did a great job, your library is magically fast. You have a lot of interesting works in the repository.
But there is one point that confuses, site virustotal claims that there is a signature for a possible attack inside the DLL.
Could you post the source code of the DLL or fix the potential threat?
Below is the text from virustotal sites:
- Matches rule Suspicious Call by Ordinal by Florian Roth at Sigma Integrated Rule Set (GitHub) Detects suspicious calls of DLLs in rundll32.dll exports by ordinal
- Matches rule Powershell Create Scheduled Task by frack113 at Sigma Integrated Rule Set (GitHub) Adversaries may abuse the Windows Task Scheduler to perform task scheduling for initial or recurring execution of malicious code
- Matches rule Failed Code Integrity Checks by Thomas Patzke at Sigma Integrated Rule Set (GitHub) Code integrity failures may indicate tampered executables. 

Thank you

**Comment by iceland2k14** [comment]
No More False +ve
