### ISSUE TITLE
ice.privatekey_to_address' function requires the private key to be a 32-byte integer

### ISSUE THREAD

**Issue by yas2yasrif** [iceland2k14/secp256k1#48]
ChatGPT says, the 'ice.privatekey_to_address' function requires the private key to be a 32-byte integer. is it right or not? can you explain?

**Comment by iceland2k14** [comment]
Yes it is 32 byte integer which is equal to 256 bit. So any issue.

**Comment by yas2yasrif** [comment]
sorry, once again a noob question...
