### ISSUE TITLE
ice.scalar_multiplications works wrong

### ISSUE THREAD

**Issue by GraverErmitage** [iceland2k14/secp256k1#53]
The function ice.scalar_multiplications([43242, 543053, 329074523, 321785444032743]) (taken from examples) provides only the result for the last value in the set.

**Comment by iceland2k14** [comment]
@GraverErmitage  No, the function is correct.
If you are looking at   Pn[-65:].hex()   This means it is just printing the last 65 bytes of the values from Pn. Try to print the full Pn and you will see all of them.
